create table ROLE(
RoleID int Primary Key,
RoleDesc varchar(20) Not null);

create table LOGIN(
USERKEY varchar(15) primary key,
PASSWORD varchar(15),
ROLEID int not null,
constraint FK_Role Foreign Key(ROLEID) REFERENCES ROLE(ROLEID)
);

create table INVESTORDETAILS(
USERKEY varchar(15),
username varchar(20),
EMAIL_ID varchar(25) unique,
PHONE_NO int unique,
ISNEWUSER int,
PAN varchar(15) Unique,
constraint FK_USERKEY Foreign Key(USERKEY) REFERENCES LOGIN(USERKEY)
);

create table ADMINBODETAILS(
USERKEY varchar(15) primary key,
username varchar(20),
EMAIL_ID varchar(25) unique,
PHONE_NO int unique,
constraint FK_USERKEY1 Foreign Key(USERKEY) REFERENCES LOGIN(USERKEY));

create table COMPANY(
COMPANYCODE INT PRIMARY KEY,
COMPANYTITLE VARCHAR(50),
OPERATIONS VARCHAR(20),
SHARECOUNT INT NOT NULL,
OPENSHAREPRICE_USD DOUBLE NOT NULL,
SECTOR VARCHAR(25),
CURRENCY VARCHAR(15),
TURNOVER DOUBLE NOT NULL);

create table STOCK(
COMPANYCODE INT,
STOCKEXCHANGE VARCHAR(20),
CURRENTPRICE DOUBLE NOT NULL,
DATE DATE NOT NULL,
TIME TIME NOT NULL,
STOCKID INT PRIMARY KEY);

create table COMMODITY(
COMMODITYCODE INT primary key,
COMMODITYNAME VARCHAR(20),
CURRENTPRICE DOUBLE NOT NULL);


create table INVESTORHISTORY(
RecId varchar(30) primary key,
USERKEY varchar(15),
DATE DATE NOT NULL,
TIME TIME NOT NULL,
COMPANYCODE INT,
constraint FK_CompCode Foreign Key(COMPANYCODE) REFERENCES COMPANY(COMPANYCODE),
constraint FK_UKey Foreign Key(USERKEY) REFERENCES INVESTORDETAILS(USERKEY)
);


Create table INVESTORSTOCKSCOMMISSIONINFO(
RECID varchar(30) primary key,
USERKEY varchar(15),
STOCKID INT,
COMPANYCODE INT,
COMMODITYCODE INT,
PRICEPAID DOUBLE,
CURRENTPRICE DOUBLE,
DATE DATE NOT NULL,
STOCKUNIT INT,
COMMODITYUNIT INT,
constraint FK_UKey1 Foreign Key(USERKEY) REFERENCES INVESTORDETAILS(USERKEY),
constraint FK_StockKey Foreign Key(STOCKID) REFERENCES STOCK(STOCKID),
constraint FK_CompCode2 Foreign Key(COMPANYCODE) REFERENCES COMPANY(COMPANYCODE),
constraint FK_ComCode Foreign Key(COMMODITYCODE) REFERENCES COMMODITY(COMMODITYCODE)
);

create table INVESTORINCOMEHISTORY(
RECID varchar(30) primary key,
USERKEY varchar(15),
DATE DATE NOT NULL,
VALUECOMMODITY DOUBLE,
VALUESTOCK DOUBLE,
constraint FK_UKey2 Foreign Key(USERKEY) REFERENCES INVESTORDETAILS(USERKEY));